# Battle against Lass Ali at Nugget Bridge
id: lass_ali_nugget_bridge
task_id: 11
game_data_version: v4.1
save_state: save_state.ss0
level_cap: 27
team_size: 3
battle_format: doubles
battle_trigger:
  - key: A
    frames: 10
allowed_team_modifications:
  - abilities
  - natures
  - moves
  - items
  - pokemon
allowed_locations:
  - pallet_town
  - route_1
  - viridian_city
  - route_22
  - route_2
  - viridian_forest
  - forest_expansion
  - diglett_cave
  - pewter_city
  - route_3
  - mt_moon_1f
  - mt_moon_b1f
  - mt_moon_b2f
  - route_4
  - cerulean_city
available_water_methods:
  - old_rod
excluded_species_categories:
  - mega
