# Battle against Archer in Mt. Moon
id: archer_mt_moon
task_id: 8
game_data_version: v4.1
save_state: save_state.ss0
level_cap: 22
team_size: 3
battle_format: singles
battle_trigger:
  - key: DOWN
    frames: 60
allowed_team_modifications:
  - abilities
  - natures
  - moves
  - items
  - pokemon
allowed_locations:
  - pallet_town
  - route_1
  - viridian_city
  - route_22
  - route_2
  - viridian_forest
  - forest_expansion
  - diglett_cave
  - pewter_city
  - route_3
  - mt_moon_1f
  - mt_moon_b1f
  - mt_moon_b2f
available_water_methods:
  - old_rod
excluded_species_categories:
  - mega
